### ISSUE TITLE
Balance jumping height

### ISSUE THREAD

**Issue by nelsonxb** [SourceComb/game-off-2016#12]
I'm not convinced that this viking jumps high enough. Sure, it's probably close-ish to a normal person's jump height right now, but we may have to make it much higher for the sake of level design.

But exactly how high should it be? 1m probably isn't enough, since he can't even make it up (or across) two tiles (which makes it impossible to branch). 2m might be better, but he still can't jump on top of something that he can walk under.

**Comment by RSteyn** [comment]
Probably quite high, since this is supposed to be a platformer of some sort.  10m/s seems pretty good.

**Comment by nelsonxb** [comment]
I can't math - what height would 10m/s result in?

**Comment by RSteyn** [comment]
Working it out now.

**Comment by RSteyn** [comment]
5m, approximately.

**Comment by nelsonxb** [comment]
Sounds good to me, as long as it looks good.
